### ISSUE TITLE
[ZCO-227] If a pinned file is opened again (while active), it opens a duplicate tab

### ISSUE THREAD

**Issue by Stakker** [czottmann/obsidian-mononote#1]
This is a very small issue, but I just noticed this, so thought I'd mention it anyway :-) Otherwise everything's been working smoothly so far 👍

Also, it seems 1.0 was released just yesterday, so congrats! Updated my BRAT to point to it, but I guess it will be found in Community Plugins soon?

<sub>[ZCO-227](https://linear.app/actionsdotwork/issue/ZCO-227/if-a-pinned-file-is-opened-again-while-active-it-opens-a-duplicate-tab)</sub>

**Comment by czottmann** [comment]
Hi @Stakker, thanks for the kind words! Yes, that issue is known, I've added a section "Known Issues" in the README a day or two ago. 😉

1.0 is out and awaiting Community Plugin review, indeed! Fingers crossed…

**Comment by saif-ellafi** [comment]
This is such a must have in Obsidian, I don't understand why that default behavior they chose. Thanks for creating this.

**Comment by yaozhenx** [comment]
This is definitely a deal-breaker. Hope it can be fixed soon.

**Comment by czottmann** [comment]
I'll look into it soon — but truth be told, Mononote is currently not my priority project, so it might take a while.

**Comment by czottmann** [comment]
I'm unable to fix this at the moment. Reason:

- When note A is focussed, and you attempt to open it in another tab, Obsidian will trigger the `file-open` event (which is what Mononote listens to).
- When note A is focussed and pinned, and you attempt to open it in another tab, Obsidian will **not** trigger the `file-open` event (so Mononote is not invoked).

I'll leave this ticket open for the time being and will revisit the issue in a couple of months.

**Comment by czottmann** [comment]
I'm unable to fix this at the moment. Reason:

* When note A is focussed, and you attempt to open it in another tab, Obsidian will trigger the `file-open` event (which is what Mononote listens to).
* When note A is focussed and pinned, and you attempt to open it in another tab, Obsidian will **not** trigger the `file-open` event (so Mononote is not invoked).

I'll revisit the issue in a couple of months.

**Comment by czottmann** [comment]
@Stakker @saif-ellafi @yaozhenx I've found a workaround which does the trick. The fix will be part of the upcoming v1.1, due soon!

**Comment by yaozhenx** [comment]
@czottmann Good to hear that. Mind to explain what the workaround is?

**Comment by czottmann** [comment]
I've completely ditched the `file-open` handler and instead focussed on the `active-leaf-change` handling which fires whenever the active tab situation changes. Opening files triggers the event (if the "Always focus new tabs" setting is on), so does switching tabs. This is working well, especially since Obsidian won't fire a `file-open` for every file or tab it opens, it's just not sufficient for what I'm trying to achieve.

That means that for Mononote to work correctly, _Settings_ → _Editor_ → **_Always focus new tabs_ must now be enabled**. More in the release notes, likely tomorrow morning.
