### ISSUE TITLE
When opening a link to a section a new instance of the same note is opened. 

### ISSUE THREAD

**Issue by 3tch-a-sketch** [czottmann/obsidian-mononote#15]
#  Recreation
Create a section within a note 
Create a link to that section 
Ctrl + Click the link 
Two instances of the same  note open

# Minimal Reproducible Example
```markdown
# example 
[[#example]]
```

# Intended Behaviour 
The section would be highlighted in yellow without opening a new instance.

**Comment by czottmann** [comment]
Thanks for the report, @3tch-a-sketch. I can't reproduce this behaviour, tho. It works as expected for me on Obsidian v1.5.3 and Mononote v1.1.1. Which versions are you on?

**Comment by 3tch-a-sketch** [comment]
You are absolutely correct. For some reason mononote was V1.0 after updating the issue is fixed.
