### ISSUE TITLE
Click on the outline title and text will flicker

### ISSUE THREAD

**Issue by Eriky-git** [czottmann/obsidian-mononote#19]
Click on the outline title and text will flicker

**Comment by czottmann** [comment]
@Eriky-git I'll need more info to verify that, because on my machine it doesn't. Which OS, Obsidian version, Mononote version, please?

**Comment by mattrmd** [comment]
I have a similar issue. I have a note pinned in the sidebar. When I use the middle mouse button to open a link twice, the second tab disappears, but the remaining tab flickers and I cannot unfocus from that tab. My note is in the right sidebar, and I have not tried it in the left sidebar.
- OS: Ubuntu 20.04
- Obsidian: 1.5.3
- Mononote: 1.1.1

There appear to be no issues in the developer console:
```
loading obsidian-auto-link-title
plugin:obsidian-tasks-plugin:149 [2024-02-04-10:01:30.999][info][tasks] loading plugin "Tasks" v6.0.0 
plugin:mononote:91 Plugin Mononote v1.1.1 initialized
```

**Comment by czottmann** [comment]
Thanks for the detailed report, @mattrmd. 

> but the remaining tab flickers and I cannot unfocus from that tab.

That sounds suspiciously like an endless loop to me. I'll take a look the next time I work on Mononote!

Mononote is currently not my highest priority, tho, so that might take a few weeks. I **will** look into it, just not right away.

**Comment by Fog3719** [comment]
https://github.com/czottmann/obsidian-mononote/assets/41268511/28758a79-bcbd-47a7-9e12-28e77d70bc45
just like this。
OS：mac os 14.1.2 (23B92)
Obsidian: 1.5.7

**Comment by czottmann** [comment]
I'll look into it during the next few days!

**Comment by MichaelLepori** [comment]
The same!

There is this issue, when your Plugin is active and I click on a linked mentions entry:

https://www.screenpresso.com/=W7P4b

Thank you.

Have a great day.

Mic.

**Comment by czottmann** [comment]
@MichaelLepori This looks like an unrelated issue; either way, I've moved it into a separate issue. If it turns out to have the same cause, great, but I'd like to prevent those unwieldy _"And also…"_ bug reports. 😅

**Comment by FynnFreyer** [comment]
Same problem, here's a screencast for documentation purposes

[screencast](https://github.com/czottmann/obsidian-mononote/assets/24855836/3b6cdf43-7250-47ff-b363-184b63aeb62c)

**Comment by czottmann** [comment]
Fixed in [Release 1.2.1](https://github.com/czottmann/obsidian-mononote/releases/tag/1.2.1). Re-open the ticket if it isn't, please!

**Comment by mattrmd** [comment]
I updated Mononote, and the issue seems to be resolved. Thanks, @czottmann !

**Comment by MichaelLepori** [comment]
Me too. Thank you @czottmann !!
