### ISSUE TITLE
[ZCO-345] [ZCO-225] Doesn't work with non-MD notes

### ISSUE THREAD

**Issue by saif-ellafi** [czottmann/obsidian-mononote#2]
Any none markdown note will not work :(

- Canvas notes will re-open duplicates.
- Image notes (PNG, JPG, etc)
- PDF notes
- Same for Excalidraw Drawing notes (plugin)

Would it be possible to not de-dup on those kind of notes?

Thank you for creating this

<sub>[ZCO-225](https://linear.app/actionsdotwork/issue/ZCO-225/doesnt-work-with-non-md-notes)</sub>

<sub>[ZCO-345](https://linear.app/actionsdotwork/issue/ZCO-345/[zco-225]-doesnt-work-with-non-md-notes)</sub>

**Comment by czottmann** [comment]
Hi @saif-ellafi, I'll look into this but it _might_ be impossible — every time a Markdown file is opened (unless it's pinned, see #1), a notification is sent out to plugins by Obsidian, and this is what Mononote works with. Mononote does not check for file type at all so my suspicion is that there is no such notification for non-MD files.

I'll look into this. Might take a while, though!

**Comment by czottmann** [comment]
I'm currently working on this.

**Comment by czottmann** [comment]
@saif-ellafi Quick update: I've implemented the requested feature. I had to jumpt through several hoops to make it work because Obsidian doesn't report opening non-MD files to the plugins. 😅 I think I found a good solution for that, though.

The new feature will be rolled out in v1.1.0, due soon!

**Comment by saif-ellafi** [comment]
brilliant, thanks!
