### ISSUE TITLE
Support links pointing to sections in a pinned note

### ISSUE THREAD

**Issue by FitzFrobozz** [czottmann/obsidian-mononote#20]
Currently, when mononote is enabled and a link pointing to a section within a pinned note is clicked, mononote prevents the note from opening in a new tab, but the user is not taken to the link destination. This is the case both when the link in question is in the pinned note (e.g. in a table of contents) and when the link is in another note (e.g. a note dragged to the sidebar). It would be wonderful if this could be changed so that the link is followed to the relevant section of the note.

**Comment by czottmann** [comment]
@FitzFrobozz I'll take a look the next time I work on Mononot!

Some expectation management: Mononote is currently not my highest priority, tho, so that might take a few weeks. I **will** look into it, just not right away.
