### ISSUE TITLE
[Bug] Ctrl+click opens the note to a new tab, causing it to flash continuously

### ISSUE THREAD

**Issue by doit132** [czottmann/obsidian-mononote#21]
[https://github.com/czottmann/obsidian-mononote/issues/19](https://github.com/czottmann/obsidian-mononote/issues/19)

[https://github.com/czottmann/obsidian-mononote/issues/21](https://github.com/czottmann/obsidian-mononote/issues/21)

Reproducible:

1. Open note via File Explorer
2. ⌘-click another note in File Explorer
3. Endless looping!

**Comment by czottmann** [comment]
@doit132 Thanks for the report, looks like the same issue as #19. I'll look into it during the next few days!

**Comment by czottmann** [comment]
Fixed in [Release 1.2.1](https://github.com/czottmann/obsidian-mononote/releases/tag/1.2.1). Re-open the ticket if it isn't, please!
