### ISSUE TITLE
Don't open a new tab, or at least close the new one, not the old one

### ISSUE THREAD

**Issue by Pato-desu** [czottmann/obsidian-mononote#22]
If you close the old one you lose where the cursor was

**Comment by czottmann** [comment]
@Pato-desu Thanks for the report. Mononote is supposed to keep the oldest tab containing that note open, so this sounds like a bug.

Actually, the flow is like this:

When the active tab changes, Mononote will look at the note in the new active tab. If there are other tabs containing that note, it will check if there is a pinned one. If there is, that one will be made active, the other unpinned tabs containing the note will be closed. If there is no pinned tab, then the oldest unpinned tab containing the note will be activated, while the other tabs are closed.

Either way, the current cursor position should be transferred to the remaining tab.

Sounds like neither of that is working for you? If not, please let me know more about your setup – open Obsidian's command palette, select "Show debug info", copy it and include it in your reply. Thanks!

**Comment by Pato-desu** [comment]
It seems to be the MAKE.md plugin, disabling it seems to fix the issues. 
I think MAKE.md it's known for bugging a bunch of others plugins.

**Comment by Pato-desu** [comment]
Yes, it's fine
