### ISSUE TITLE
[BUG] Mononote 1.2.1 won't switch when normal click (left click) in file explorer

### ISSUE THREAD

**Issue by l2eused** [czottmann/obsidian-mononote#27]
step to reproduce:
- open `A` note
- open `B` note in new tab
- left click `A` note to open in same tab (currently is `B` note in tab)

actual behavior:
`B` note in tab will switch to `A` note tab and switch back...

expected behavior:
it should switch to `A` note tab and shouldn't switch it back.

https://github.com/czottmann/obsidian-mononote/assets/94383254/e8d1c4d9-f9d8-4fca-885b-8fc955a1242a

platforms:
windows 10
obsidian 1.6.3
mononote 1.2.1

this is all my plugin...
- [⬇️](obsidian://SP-install?id=obsidian-auto-link-title&enable=true) [**Auto Link Title**](https://obsidian.md/plugins?id=obsidian-auto-link-title) by [*Matt Furden*](https://github.com/zolrath) ^[This plugin automatically fetches the titles of links from the web]
- [⬇️](obsidian://SP-install?id=calendar&enable=true) [**Calendar**](https://obsidian.md/plugins?id=calendar) by [*Liam Cain*](https://github.com/liamcain/) ^[Calendar view of your daily notes]
- [⬇️](obsidian://SP-install?id=cmdr&enable=true) [**Commander**](https://obsidian.md/plugins?id=cmdr) by [*jsmorabito & phibr0*](https://github.com/phibr0) [♡](https://ko-fi.com/phibr0) ^[Customize your workspace by adding commands everywhere, create Macros and supercharge your mobile toolbar.]
- [⬇️](obsidian://SP-install?id=obsidian42-brat&enable=true) [**BRAT**](https://obsidian.md/plugins?id=obsidian42-brat) by [*TfTHacker*](https://github.com/TfTHacker/obsidian42-brat) [♡](https://bit.ly/o42-kofi)/[♡](https://tfthacker.com) ^[Easily install a beta version of a plugin for testing.]
- [⬇️](obsidian://SP-install?id=periodic-notes&enable=true) [**Periodic Notes**](https://obsidian.md/plugins?id=periodic-notes) by [*Liam Cain*](https://github.com/liamcain/) ^[Create/manage your daily, weekly, and monthly notes]
- [⬇️](obsidian://SP-install?id=darlal-switcher-plus&enable=true) [**Quick Switcher++**](https://obsidian.md/plugins?id=darlal-switcher-plus) by [*darlal*](https://github.com/darlal/obsidian-switcher-plus) ^[Enhanced Quick Switcher, search open panels, and symbols.]
- [⬇️](obsidian://SP-install?id=recent-files-obsidian&enable=true) [**Recent Files**](https://obsidian.md/plugins?id=recent-files-obsidian) by [*Tony Grosinger*](https://grosinger.net) [♡](https://github.com/sponsors/tgrosinger)/[♡](https://buymeacoffee.com/tgrosinger)/[♡](https://paypal.me/tgrosinger) ^[List files by most recently opened]
- [⬇️](obsidian://SP-install?id=snippet-commands-obsidian&enable=true) [**Snippet Commands**](https://obsidian.md/plugins?id=snippet-commands-obsidian) by [*death_au*](https://github.com/deathau) ^[Registers custom css snippets as commands (which you can bind hotkeys to)]
- [⬇️](obsidian://SP-install?id=templater-obsidian&enable=true) [**Templater**](https://obsidian.md/plugins?id=templater-obsidian) by [*SilentVoid*](https://github.com/SilentVoid13) ^[Create and use templates]
- [⬇️](obsidian://SP-install?id=obsidian-theme-design-utilities&enable=true) [**Theme Design Utilities**](https://obsidian.md/plugins?id=obsidian-theme-design-utilities) by [*pseudometa*](https://github.com/chrisgrieser/theme-design-utilities) [♡](https://ko-fi.com/pseudometa) ^[Some Utilities and Quality-of-Life Features for Designers of Obsidian Themes.]
- [⬇️](obsidian://SP-install?id=tag-wrangler&enable=true) [**Tag Wrangler**](https://obsidian.md/plugins?id=tag-wrangler) by [*PJ Eby*](https://github.com/pjeby) [♡](https://dirtsimple.org/tips/tag-wrangler) ^[Rename, merge, toggle, and search tags from the tag pane]
- [⬇️](obsidian://SP-install?id=settings-search&enable=true) [**Settings Search**](https://obsidian.md/plugins?id=settings-search) by [*Jeremy Valentine*](https://github.com/valentine195) ^[Globally search settings in Obsidian.md]
- [⬇️](obsidian://SP-install?id=nifty-links&enable=true) [**Nifty Links**](https://obsidian.md/plugins?id=nifty-links) by [*x-Ai*](https://github.com/x-Ai) ^[Generate elegant, Notion-style rich link cards to enhance your note-taking experience]
- [⬇️](obsidian://SP-install?id=external-links&enable=true) [**External Links**](https://obsidian.md/plugins?id=external-links) by [*Juan Vimberg*](https://github.com/jivimberg/) ^[List external links and discover which notes reference them.]
- [⬇️](obsidian://SP-install?id=obsidian-style-settings&enable=true) [**Style Settings**](https://obsidian.md/plugins?id=obsidian-style-settings) by [*mgmeyers*](https://github.com/mgmeyers/obsidian-style-settings) ^[Offers controls for adjusting theme, plugin, and snippet CSS variables.]
- [⬇️](obsidian://SP-install?id=obsidian-better-command-palette&enable=true) [**Better Command Palette**](https://obsidian.md/plugins?id=obsidian-better-command-palette) by [*Alex Bieg*](www.github.com/AlexBieg) ^[A command palette that does all of the things you want it to do.]
- [⬇️](obsidian://SP-install?id=quick-preview&enable=true) [**Quick Preview**](https://obsidian.md/plugins?id=quick-preview) by [*Ryota Ushio*](https://github.com/RyotaUshio) [♡](https://www.buymeacoffee.com/ryotaushio) ^[Quickly preview a suggestion before selecting it in link suggestions & quick switcher.]
- [⬇️](obsidian://SP-install?id=cycle-through-panes&enable=true) [**Tab Switcher**](https://obsidian.md/plugins?id=cycle-through-panes) by [*Vinzent & phibr0*](https://github.com/Vinzent03) [♡](https://ko-fi.com/vinzent) ^[Switch your tabs with Ctrl + Tab in recently used order like in a browser.]
- [⬇️](obsidian://SP-install?id=tab-navigator&enable=true) [**Tab Navigator**](https://obsidian.md/plugins?id=tab-navigator) ^[Simple Tab Switcher, search open tabs.]
- [⬇️](obsidian://SP-install?id=folder-notes&enable=true) [**Folder notes**](https://obsidian.md/plugins?id=folder-notes) by [*Lost Paul*](https://github.com/LostPaul) [♡](https://ko-fi.com/paul305844) ^[Create notes within folders that can be accessed without collapsing the folder, similar to the functionality offered in Notion.]
- [⬇️](obsidian://SP-install?id=painter&enable=true) [**Painter**](https://obsidian.md/plugins?id=painter) by [*KraXen72 and Chetachi Ezikeuzor*](https://github.com/KraXen72) [♡](https://ko-fi.com/kraxen72) ^[Paint text different colors]
- [⬇️](obsidian://SP-install?id=unicode-search&enable=true) [**Unicode Search**](https://obsidian.md/plugins?id=unicode-search) by [*BambusControl*](https://github.com/BambusControl) ^[Search and insert Unicode characters into your editor]
- [⬇️](obsidian://SP-install?id=table-extended&enable=true) [**Table Extended**](https://obsidian.md/plugins?id=table-extended) by [*AidenLx*](https://github.com/AidenLx/) ^[Enable extended table support with MultiMarkdown 6 syntax]
- [⬇️](obsidian://SP-install?id=obsidian-image-toolkit&enable=true) [**Image Toolkit**](https://obsidian.md/plugins?id=obsidian-image-toolkit) by [*sissilab*](https://github.com/sissilab) ^[This plugin provides some image viewing toolkit.]
- [⬇️](obsidian://SP-install?id=obsidian-plugin-update-tracker&enable=true) [**Plugin Update Tracker**](https://obsidian.md/plugins?id=obsidian-plugin-update-tracker) ^[Know when installed plugins have updates and evaluate the risk of upgrading]
- [⬇️](obsidian://SP-install?id=dataview&enable=true) [**Dataview**](https://obsidian.md/plugins?id=dataview) by [*Michael Brenan*](https://github.com/blacksmithgu) ^[Complex data views for the data-obsessed.]
- [⬇️](obsidian://SP-install?id=obsidian-kanban&enable=true) [**Kanban**](https://obsidian.md/plugins?id=obsidian-kanban) by [*mgmeyers*](https://github.com/mgmeyers/obsidian-kanban) ^[Create markdown-backed Kanban boards in Obsidian.]
- [⬇️](obsidian://SP-install?id=obsidian-linter&enable=true) [**Linter**](https://obsidian.md/plugins?id=obsidian-linter) by [*Victor Tao*](https://github.com/platers) ^[Formats and styles your notes. It can be used to format YAML tags, aliases, arrays, and metadata; footnotes; headings; spacing; math blocks; regular markdown contents like list, italics, and bold styles; and more with the use of custom rule options as well.]
- [⬇️](obsidian://SP-install?id=omnisearch&enable=true) [**Omnisearch**](https://obsidian.md/plugins?id=omnisearch) by [*Simon Cambier*](https://github.com/scambier/obsidian-omnisearch) [♡](https://github.com/sponsors/scambier)/[♡](https://ko-fi.com/scambier) ^[A search engine that just works]
- [⬇️](obsidian://SP-install?id=obsidian-reading-time&enable=true) [**Reading Time**](https://obsidian.md/plugins?id=obsidian-reading-time) by [*avr*](https://github.com/avr) ^[Add the current note's reading time to Obsidian's status bar.]
- [⬇️](obsidian://SP-install?id=obsidian-banners&enable=true) [**Banners**](https://obsidian.md/plugins?id=obsidian-banners) by [*Noatpad*](https://github.com/noatpad/obsidian-banners) ^[Add banner images to your notes!]
- [⬇️](obsidian://SP-install?id=obsidian-sequence-hotkeys&enable=true) [**Sequence Hotkeys**](https://obsidian.md/plugins?id=obsidian-sequence-hotkeys) by [*Ruan Moolman*](https://github.com/moolmanruan) ^[This plugin allows you to set hotkeys with key sequences instead of a single chord.]
- [⬇️](obsidian://SP-install?id=remember-cursor-position&enable=true) [**Remember cursor position**](https://obsidian.md/plugins?id=remember-cursor-position) by [*Dmitry Savosh*](https://github.com/dy-sh/) ^[Remember cursor and scroll position for each note]
- [⬇️](obsidian://SP-install?id=obsidian-text-format&enable=true) [**Text Format**](https://obsidian.md/plugins?id=obsidian-text-format) by [*Benature*](https://github.com/Benature) [☕️](https://www.buymeacoffee.com/benature)/[⚡️](https://afdian.net/a/Benature-K)/[♡](https://s2.loli.net/2024/01/30/jQ9fTSyBxvXRoOM.png) ^[Format text such as lowercase/uppercase/capitalize/titlecase, converting order/bullet list, removing redundant spaces/newline characters.]
- [⬇️](obsidian://SP-install?id=novel-word-count&enable=true) [**Novel word count**](https://obsidian.md/plugins?id=novel-word-count) by [*Isaac Lyman*](https://isaaclyman.com) [♡](https://ko-fi.com/isaaclyman) ^[Displays a word count (and more!) for each file, folder and vault in the File Explorer pane.]
- [⬇️](obsidian://SP-install?id=image-converter&enable=true) [**Image Converter**](https://obsidian.md/plugins?id=image-converter) by [*xRyul*](https://github.com/xryul) ^[Convert, compress and resize images from one format to another by dragging and dropping or pasting into the note.]
- [⬇️](obsidian://SP-install?id=various-complements&enable=true) [**Various Complements**](https://obsidian.md/plugins?id=various-complements) by [*tadashi-aikawa*](https://github.com/tadashi-aikawa) ^[This plugin enables you to complete words like the auto-completion of IDE]
- [⬇️](obsidian://SP-install?id=obsidian-footnotes&enable=true) [**Footnote Shortcut**](https://obsidian.md/plugins?id=obsidian-footnotes) by [*Alexis Rondeau, Micha Brugger, Jason Qin*](https://publish.obsidian.md/alexisrondeau) ^[Insert and write footnotes faster]
- [⬇️](obsidian://SP-install?id=obsidian-icon-folder&enable=true) [**Iconize**](https://obsidian.md/plugins?id=obsidian-icon-folder) by [*Florian Woelki*](https://florianwoelki.com/) ^[Add icons to anything you desire in Obsidian, including files, folders, and text.]
- [⬇️](obsidian://SP-install?id=emoji-magic&enable=true) [**Emoji Magic**](https://obsidian.md/plugins?id=emoji-magic) by [*simplgy*](https://github.com/simplgy) ^[Easily add emoji, with a powerful keyword search. 🔮 ✨ 🐇]
- [⬇️](obsidian://SP-install?id=obsidian-wordnet-plugin&enable=true) [**WordNet Dictionary**](https://obsidian.md/plugins?id=obsidian-wordnet-plugin) by [*TfT Hacker*](https://github.com/TfTHacker/Obsidian-WordNet) ^[WordNet is a large lexical database of English developed by Princeton University.]
- [⬇️](obsidian://SP-install?id=global-search-and-replace&enable=true) [**Global Search and Replace**](https://obsidian.md/plugins?id=global-search-and-replace) by [*Mahmoud Fawzy Khalil*](https://github.com/MahmoudFawzyKhalil/) ^[Search and replace in all vault files]
- [⬇️](obsidian://SP-install?id=simple-canvasearch&enable=true) [**Simple CanvaSearch**](https://obsidian.md/plugins?id=simple-canvasearch) by [*ddalexb*](https://github.com/ddalexb) ^[Quickly fuzzy-search and shift focus to notes or cards within the currently opened canvas.]
- [⬇️](obsidian://SP-install?id=mononote&enable=true) [**Mononote**](https://obsidian.md/plugins?id=mononote) by [*Carlo Zottmann*](https://github.com/czottmann) ^[Ensures each note occupies only one tab. If a note is already open, its existing tab will be focussed instead of opening the same file in the current tab.]
- [⬇️](obsidian://SP-install?id=pane-relief&enable=true) [**Pane Relief**](https://obsidian.md/plugins?id=pane-relief) by [*PJ Eby*](https://github.com/pjeby) ^[Per-tab history, hotkeys for pane/tab movement, navigation, sliding workspace, and more]
- [⬇️](obsidian://SP-install?id=share-my-plugin-list&enable=true) [**Share my plugin list**](https://obsidian.md/plugins?id=share-my-plugin-list) by [*Benature*](https://github.com/Benature) [☕️](https://www.buymeacoffee.com/benature)/[⚡️](https://afdian.net/a/Benature-K)/[♡](https://s2.loli.net/2024/01/30/jQ9fTSyBxvXRoOM.png) ^[Share the enabled plugins in list/table format.]

**Comment by czottmann** [comment]
Thanks for the report, @l2eused!

I'm quite sure it's a race condition. The way Obsidian signals tab switching internally made it necessary to implement some time-based guess work in Mononote. In a nutshell: For some operations, Mononote simply waits for 100ms before applying its own tab switching rules, to give Obsidian time to work things out. If it isn't enough time, then Mononote will switch tabs from T1 to T2 _before_ Obsidian is done, and once Obsidian _is_ done, the app itself switches back to T1.

I suspected that depending on your machine and your vault size, 100ms might not be enough time. Raising that number too much, however, might be annoying for people with fast machines and small vaults – so I tried to find a good middle ground.

I'll add a settings page in the next release that lets you configure your sweet spot, which should mitigate the issue you're seeing!

**Comment by czottmann** [comment]
Give [Release 1.2.2 · czottmann/obsidian-mononote](https://github.com/czottmann/obsidian-mononote/releases/tag/1.2.2) a spin, and try increasing the delay configuration:

![CleanShot 2024-06-24 at 14 31 43@2x](https://github.com/czottmann/obsidian-mononote/assets/1501/759cb49f-fa6b-4b8f-b0b1-265a3a645653)

If that doesn't do the trick, please re-open this ticket! 🖖🏼
