### ISSUE TITLE
[ZCO-226] Feature request: Support for anchor links

### ISSUE THREAD

**Issue by awsharif** [czottmann/obsidian-mononote#3]
Hi,

This plugin does a great job at what should be default behaviour, IMO. Thanks for the great work.

I have an issue where opening a block link to an already open file. In normal Obsidian behaviour this results in open file > direct navigation to relevant block (highlighted). With mononote, I think because the functionality involves closing the new instance in favour of the already open one, block links do not work as expected. I hope this makes sense.

<sub>[ZCO-226](https://linear.app/actionsdotwork/issue/ZCO-226/feature-request-support-for-anchor-links)</sub>

**Comment by czottmann** [comment]
Hi @awsharif, thanks for the report!

> With mononote, I think because the functionality involves closing the new instance in favour of the already open one, block links do not work as expected.

Yes, that's exactly what it does. I never thought about including support for block links as I don't use them myself. I'll change your ticket here and make it a feature request so I won't forget taking a stab at it. (This might take a while, tho, as I'm currently in the middle of another project which has a higher priority.)

**Comment by jiajiala** [comment]
Wait for this function

**Comment by czottmann** [comment]
@awsharif @jiajiala I've just implemented a fix. It will be part of the upcoming v1.1, due soon!
