### ISSUE TITLE
[ZCO-257] Prevent closing pinned tabs

### ISSUE THREAD

**Issue by d9k** [czottmann/obsidian-mononote#4]
Sometimes it's required to work with several copies of one tab (different scroll positions).

Legend:

- `A`: tab
- `>A`: selected tab
- `[A]`: pinned tab
- `>[A]`: selected pinned tab

Steps to reproduce:

0) Imagine we have Obsidian splitted by two halves. With tabs:
  -  `I. A, >B`; `II. C, >D`
1) Open new tab `N` in right Obsidian half:
  - `I. A, >B` ; `II. C, D, >N`
2) Pin this tab to prevent close:
  - `I. A, >B`; `II. C, D, >[N]`
3) Run "split down" or "split right" command. Now Obsidian is splitted by three parts. We have two copies of `A`: 
  - `I. A, >B`; `II. C, D, >[N]`, `III. >N`
4) Pin tab copy to prevent close
  - `I. A, >B`; `II. C, D, >[N]`, `III. >[N]`
5) Don't want to have Obsidian splitted by three parts. Two parts are enough. So move tab copy (3rd) to left Obsidian half. Now we have two tabs:
  -  `I. A, B, >[N]`; `II. C, D, >[N]`
6) Now we have to work with tab B. Let's switch to it:
  -  `I. A, >B, [N]`; `II. C, D, >[N]`
7) Now we finished to work with tab B. We want to work again with two copies of tab `N`. So we switch back to tab `[N]` in left Obsidian half. And it disappears! 😠
   - Expected: 
     -  `I. A, B, >[N]`; `II. C, D, >[N]` 
   - Actual: `I. A, B, >[N]`; `II. C, D, >[N]` 
     -  `I. A, >B`; `II. C, D, >[N]` 

Please just DON'T CLOSE PINNED TABS.
If we have any number of pinned tabs they must be preserved. Close not pinned tabs only!!

<sub>[ZCO-257](https://linear.app/actionsdotwork/issue/ZCO-257/dont-close-pinned-tab)</sub>

**Comment by d9k** [comment]
Added pull request #5

**Comment by d9k** [comment]
My  fix adds new problem:

- `8.` Select `B` on left Obsidian half again:
  - `I. A, >B, [N]`; `II. C, D, >[N]`
- `8.` Just click on Obsidian right half: suddenly `[N]` becomes selected on left half! 
  - Expected:
    -  `I. A, >B, [N]; II. C, D, >[N]`
 - Actual:
    -  `I. A, B, >[N]; II. C, D, >[N]`



Closed MR for now.

**Comment by d9k** [comment]
fixed PR

**Comment by czottmann** [comment]
Hi @d9k, thanks for the report and the detailed test case and everything! Nice work. I'll have to look into this, and **I will**, just not right away, as Mononote is not my highest priority at the moment.

**Comment by d9k** [comment]
[Quick Switcher++ plugin](https://github.com/darlal/obsidian-switcher-plus)](https://github.com/darlal/obsidian-switcher-plus) mostly solves duplicate tab problem

**Comment by czottmann** [comment]
Pull request accepted, ran into smaller issues when trying to merge, ended up copying your one-liner into the new work branch manually. Commit message contains attribution. Thanks again, @d9k!

Fix will be in the upcoming v1.1.

**Comment by czottmann** [comment]
Fixed in [https://github.com/czottmann/obsidian-mononote/commit/9c14deb2de93a1b8cf23d9b9bb6bef1625acef4c](https://github.com/czottmann/obsidian-mononote/commit/9c14deb2de93a1b8cf23d9b9bb6bef1625acef4c)
