### ISSUE TITLE
[ZCO-346] [ZCO-302] Autoswitch to existing tab when previewing a link If Hover Edit plugin is active

### ISSUE THREAD

**Issue by yan42685** [czottmann/obsidian-mononote#7]
Hi czottmann,

Thanks for making such a handy plugin. I've noticed an issue with `mononote` when used alongside the `Hover Editor` plugin. When both are active, previewing a link will automatically lead to a switch to an existing tab.

![test](https://uploads.linear.app/7df2165d-5920-4338-950f-f2b7152a3c02/a3f73cb3-c8ea-480a-9a9a-9e44f8a03120/c142b16d-a1ad-424b-80b8-e95c7f5a38cd?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzdkZjIxNjVkLTU5MjAtNDMzOC05NTBmLWYyYjcxNTJhM2MwMi9hM2Y3M2NiMy1jOGVhLTQ4MGEtOWE5YS05ZTQ0ZjhhMDMxMjAvYzE0MmIxNmQtYTFhZC00MjRiLTgwYjgtZTk1YzdmNWEzOGNkIiwiaWF0IjoxNzAxODU5NDQyLCJleHAiOjE3MDE5NDU4NDJ9.s8Tg4E0SWbxeMlsokhdagEjHVH2HJh-SQWfjhjAh0ps)

<sub>From [SyncLinear.com](https://synclinear.com) | [ZCO-302](https://linear.app/actionsdotwork/issue/ZCO-302/[bug]-autoswitch-to-existing-tab-when-previewing-a-link-if-hover-edit)</sub>

<sub>[ZCO-346](https://linear.app/actionsdotwork/issue/ZCO-346/[zco-302]-autoswitch-to-existing-tab-when-previewing-a-link-if-hover)</sub>

**Comment by czottmann** [comment]
Thanks, @yan42685, I'll look into it! Good report, by the way, appreciate the effort you made 🙏🏼

**Comment by czottmann** [comment]
@yan42685 The fix will be part of the upcoming v1.1, due soon!

**Comment by yan42685** [comment]
Thank you for your great work on Mononote, which makes this plugin better! My apologies for the delayed response. I wanted to ensure that the new version of my plugin, Clever Search, was more refined before sharing it with you, as I didn't want to disappoint you despite it still being in the early stages. Clever Search has now launched its 0.1 version, supporting whole-library search. If you're interested, feel free to check it out!

![image](https://github.com/czottmann/obsidian-mononote/assets/41834091/5489497c-7d2a-4b48-b8af-5d22402f8955)

Here is the link: https://github.com/yan42685/obsidian-clever-search
